### ISSUE TITLE
Comply with the Gherkin Licence

### ISSUE THREAD

**Issue by aslakhellesoy** [vowsjs/kyuri#1]
You are not: http://github.com/aslakhellesoy/gherkin/blob/master/LICENSE

You have lifted i18n.yml (and various .feature files) without making sure Gherkin's LICENCE follows along.
Instead of copying the i18n.yml file (and risking being out of date), I suggest you make a code generator that depends on the gherkin gem as described here: http://wiki.github.com/aslakhellesoy/gherkin/tool-support (See the Tool Support section).

**Comment by Marak** [comment]
Will fix immediately, sorry for the lapse. This was a rushed entry for nodeknockout :-)

We actually have a code generator here, http://github.com/nodejitsu/kyuri/blob/master/src/i18n-generator.rb.

We really love Cucumber! Thanks for taking a look at our project.

**Comment by Marak** [comment]
I think I have added proper attribution to the project. Please review and let me know if you require any additional changes. http://github.com/nodejitsu/kyuri/commit/1bb3295a6725b68699223ae751a0acdb2f6d4096#commitcomment-139092

**Comment by aslakhellesoy** [comment]
Looks good :-)
