### ISSUE TITLE
Support PyStrings

### ISSUE THREAD

**Issue by aslakhellesoy** [vowsjs/kyuri#2]
-Or stop claiming gherkin compliance (in README.md and possibly other places). You can't do this yet, can you?

<pre>
Given I have the following poem:
  """
  old pond
  a frog leaps in
  water’s sound
  """
</pre>

**Comment by Marak** [comment]
aslakhellesoy, there is lot of things we didn't get the chance to implement. 

please let me know what we can do to further get gherkin complaint. if you'd like i can add a warning message or change the readme.

our goal is to become 100% gherkin complaint. please remember this was created in 48 hours for the nodeknockout coding competition. as soon as indexzero is available, he will be pushing more commits to this repo.

**Comment by Marak** [comment]
okay, added warning in readme. http://github.com/nodejitsu/kyuri/commit/67b72024a35a90859dc05bbda61950923c0c26e7

will continue to work on this ticket.

**Comment by aslakhellesoy** [comment]
Didn't mean to sound negative. What you have done is super impressive! It would be interesting to run gherkin's own test suite (cucumber features) against your parser. And if it's good I wouldn't be opposed to have it part of the gherkin codebase.

After all - we've had this for 9 months now: http://github.com/aslakhellesoy/gherkin/issues#issue/38

**Comment by Marak** [comment]
:-)

**Comment by indexzero** [comment]
Definitely interested in putting Kyuri in the cucumber codebase. Using rednode seems prudent for testing the Kyuri parser itself, but ideally I'd like pure javascript users of Kyuri to not have to take any Ruby dependencies. Could we setup Kyuri to be downstream from cucumber via a git submodule or something similar?

**Comment by Marak** [comment]
is this fixed now?

**Comment by indexzero** [comment]
No. They are lexed and parsed now, but nothing is done with them in code generation. It's actually somewhat unclear to me what PyStrings function are in generated code. aslakhellesoy can you clarify this for me? Do they have any special function besides multi-line documentation?

**Comment by aslakhellesoy** [comment]
They are explained here: http://wiki.github.com/aslakhellesoy/cucumber/multiline-step-arguments

Does that answer your question?

Re: downstream - sounds great.

**Comment by indexzero** [comment]
Ok, That definitely clears it up. I guess it is done in that case because it gets placed into the AST now. We're not generating step definitions yet, but we will be soon. 

I'm probably going to make Kyuri a standalone binary that acts as a custom test runner for vows among other things. To see what I'm talking about, you can check out our company blog:
http://blog.nodejitsu.com/vows-custom-test-runner
