### ISSUE TITLE
Create javascript based step definitions

### ISSUE THREAD

**Issue by indexzero** [vowsjs/kyuri#4]
We should be creating javascript step definitions. Something like: 

<pre>
Given(/I have entered (d+) into the calculator/, function () {

});
</pre>

**Comment by paulbjensen** [comment]
+1

**Comment by indexzero** [comment]
This is actually done in the 0.2.0 branch, but not well tested. Give it a shot if you're up for it

**Comment by dalssoft** [comment]
+1

**Comment by indexzero** [comment]
Fixed in `kyuri@0.2.0`
