### ISSUE TITLE
Minimal developer's guide

### ISSUE THREAD

**Issue by aslakhellesoy** [vowsjs/kyuri#7]
I'm about to start hacking on kyuri, but I'm stuck on several levels:
- What command do I run to run all the tests?
- What packages do I need to install?
- What package manager should I use to install them? (npm?)

I know Javascript, but the node ecosystem is new to me, so I need some hand holding to get started here.

A couple of sections in the README please :-)

BTW, I can't wait to get knee-deep into this.

**Comment by indexzero** [comment]
Like the enthusiasm :)

So you can run the tests using vows:

<pre>
vows test/lexer-test.js test/parser-test.js test/generator-test.js
</pre>


Right now the test assertions are kind of useless, I've just been inspecting the output as I get all the pieces working together. 

You should install npm then install the required packages and clone the repo:

<pre>
curl http://npmjs.org/install.sh | sudo sh
sudo npm install eyes vows underscore
git clone git://github.com/nodejitsu/kyuri.git
</pre>


Let me know if you run into any issues.

**Comment by Marak** [comment]
there is also a kyuri package (which should resolve all deps) that can be installed via npm

```
 npm install kyuri
```

but its not going to be up to date since we are in active dev right now

**Comment by indexzero** [comment]
You don't want to npm install kyuri for development purposes, just clone the repo. We haven't pushed to npm since node knockout.
