### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by masylum** [vowsjs/kyuri#9]
I never used cucumber before and I'm probably missing the most basic important part of kyuri butt..

How does it work? Once I write a feature, how can I convert it to a vows test?
I would expect to do $ kyuri foo.feature, but there is no bin.

**Comment by Marak** [comment]
we are actively working on getting a binary together so you can call kyuri from the command line. there is a good example bin for this in the vows project.

right now kyuri is mostly focused on being a gherkin parser in javascript. we definitely need to add more tools. commits are welcome.

**Comment by indexzero** [comment]
Reopened as issue 10
